-- this configuration requires neovim >= 0.12 (vim.pack)
-- core
require("options")
require("keymaps")
require("statusline")
require("autocmds")
-- plugins
require("plugins.plenary")
require("plugins.ts-rstml")
require("plugins.lsp")
require("plugins.ui")
require("plugins.blink")
require("plugins.oil")
require("plugins.flash")
require("plugins.colorscheme")
require("plugins.pick")
require("plugins.git")
require("plugins.pairs")
require("plugins.surround")
require("plugins.typst-preview")
require("plugins.luasnip")
require("plugins.auto-tag")
require("plugins.conform")
require("plugins.ai")
require("plugins.null_ls")
require("plugins.windsurf")
require("plugins.render_markdown")
