-- Options
vim.o.guicursor = "i:block" -- Use block cursor in insert mode
-- vim.o.colorcolumn = "80" -- Highlight column 80
vim.o.signcolumn = "yes:1" -- Always show sign column
vim.o.termguicolors = true -- Enable true colors
vim.o.ignorecase = true -- Ignore case in search
vim.o.smartcase = true --
vim.o.swapfile = false -- Disable swap files
vim.o.autoindent = true -- Enable auto indentation
vim.o.expandtab = true -- Use spaces instead of tabs
vim.o.tabstop = 4 -- Number of spaces for a tab
vim.o.softtabstop = 4 -- Number of spaces for a tab when editing
vim.o.shiftwidth = 4 -- Number of spaces for autoindent
vim.o.shiftround = true -- Round indent to multiple of shiftwidth
vim.o.listchars = "tab: ,multispace:|   ," -- Characters to show for tabs, spaces, and end of line
vim.o.list = true -- Show whitespace characters
vim.o.number = true -- Show line numbers
vim.o.relativenumber = true -- Show relative line numbers
vim.o.numberwidth = 2 -- Width of the line number column
vim.o.wrap = false -- Disable line wrapping
vim.o.cursorline = true -- Highlight the current line
vim.o.scrolloff = 8 -- Keep 8 lines above and below the cursor
vim.o.inccommand = "nosplit" -- Shows the effects of a command incrementally in the buffer
vim.o.undodir = os.getenv('HOME') .. '/.vim/undodir' -- Directory for undo files
vim.o.undofile = true -- Enable persistent undo
vim.o.winborder = "none" -- none - single - double - rounded - solid - shadow
vim.o.hlsearch = true -- Enable/Disable highlighting of search results
vim.opt.completeopt = { "menuone", "popup", "noinsert" } -- Options for completion menu
